
<div id="footer">

<div class="contactHeading">Contact</div>
<div class="footerHolder">
	<div class="footerLeft">
    	<p class="left">Address:</p>
        <p class="right">123 Street St<br /> Vancouver BC<br /> Canada</p>
    </div>
    
    <div class="footerRight">
    	<p class="left">Téléphone: <br /> Fax: <br />Email: <br /> Twitter:</p>
	    <p class="right">1 800 600 0000 <br /> 1 800 600 0000 <br /> organic@organic.com <br /> @organics</p>
    </div>
    <div class="clear"></div>
</div>
</div>
</div>

</div><!-- Main ends here -->
</body>
</html>
