<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title> </title>
        <link href="templates/default/css/style.css" rel="stylesheet" type="text/css" />

        <!--[if lte IE 6]>
                <script type="text/javascript" src="supersleight-min.js"></script>
            <link href="templates/default/css/ie6.css" rel="stylesheet" type="text/css" />
        <![endif]-->
    </head>
    <body>
        <div id="main">
            <div id="header">
                <div class="searchBar">
                    <div class="search">
                        <div class="txt"><input type="text" /></div>
                        <div class="searchBt"><input type="button" value="search" /></div>
                    </div>
                    <div class="signIn">Connexion</div>
                </div>

                <div class="logo">
                    <a href="#"><img src="templates/default/images/logo.png" alt="" /></a>
                </div>

                <div class="menu">
                    <ul id="menu">
                        <li class="home"><a href=".">Accueil</a></li>
                        <li class="commit"><a href="product">Notre Catalogue</a></li>
                        <li class="organic"><a href="#">Extras</a></li>
                        <li class="contact"><a href="#">Contact</a></li>
                    </ul>
                </div>
                <div class="subs">
                    <p>RSS</p><img src="templates/default/images/rss.png" alt="" />
                </div>
            </div><!-- Header ends here -->

            <div class="clear"></div>
            <div id="content">
                <div class="welcomeHolder">
                    <div class="welcome">
                        <img src="templates/default/images/img01.jpg" alt="" />
                        <h1>Welcome to Organics</h1>
                        <p><em>Introduce your company here. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </em></p>  
                        <p align="right"><input type="button" value="Consulter nos offres" class="view" /></p> 
                        <div class="clear"></div>
                    </div>
                    <div class="welcomeBottom"></div>
                </div>

                <div class="heading">Why Organic?</div>
                <div class="organic">
                    <div class="organicHolder">
                        <div class="organicContent">
                            <img src="templates/default/images/img02.jpg" alt="" />
                            <h2>Header One</h2>
                            <p>Organic fruit and vegetables Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </p>
                        </div>
                    </div>

                    <div class="organicHolder">
                        <div class="organicContent">
                            <img src="templates/default/images/img03.jpg" alt="" />
                            <h2>Header Two</h2>
                            <p>Organic fruit and vegetables Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </p>
                        </div>
                    </div>

                    <div class="organicHolder">
                        <div class="organicContent">
                            <img src="templates/default/images/img04.jpg" alt="" />
                            <h2>Header Three</h2>
                            <p>Organic fruit and vegetables Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim </p>
                        </div>
                    </div>
                </div>

                <div class="space"></div>

                <div class="organic">
                    <div class="organicHolder">
                        <div class="organicContent">
                            <img src="templates/default/images/img05.jpg" alt="" />
                            <h2>Header Four</h2>
                            <p>Organic fruit and vegetables Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
                        </div>
                    </div>

                    <div class="organicHolder">
                        <div class="organicContent">
                            <img src="templates/default/images/img06.jpg" alt="" />
                            <h2>Header Five</h2>
                            <p>Organic fruit and vegetables Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim </p>
                        </div>
                    </div>

                    <div class="organicHolder">
                        <div class="vegetable">
                            <h3>Learn About Our Organic Vegetables</h3>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>

                <div class="hr"></div>
                <div class="space"></div>