<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link href="../../templates/default/css/admin.css" rel="stylesheet" type="text/css" media="" />
    </head>
    <body>
       	<div class="lg-container">
            <h1>Administration</h1>
            <form action="" id="lg-form" name="lg-form" method="post">
                <div>
                    <label for="username">Username:</label>
                    <input type="text" name="user_name" id="username" placeholder="identifiant"/>
                </div>

                <div>
                    <label for="password">Password:</label>
                    <input type="password" name="user_password" id="password" placeholder="mot de passe" />
                </div>

                <div>				
                    <button type="submit" id="login">Connexion</button>
                </div>

            </form>
            <div id="message"></div>
        </div>
    </body>
</html>
