<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="{$lang_iso}">
	<head>
		<title></title>
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />
		<meta name="generator" content="PrestaShop" />
		<meta name="robots" content="index,follow" />
		<link rel="icon" type="image/vnd.microsoft.icon" href="" />
		<link rel="shortcut icon" type="image/x-icon" href="" />
	
	<link href="<?php echo url::get_template_path();?>css/style.css" rel="stylesheet" type="text/css" media="" />
	<script type="text/javascript" src=""></script>
	</head>
	
	<body >
		<div id="restricted-country">
			<p> <span class="bold"></span></p>
		</div>
		<div id="page">

			<!-- Header -->
			<div id="header">
				<a id="header_logo" href="" title="">
					<img class="logo" src="" alt="" />
				</a>
				<div id="header_right">
				</div>
			</div>

			<div id="columns">
				<!-- Left -->
				<div id="left_column" class="column">
				</div>

				<!-- Center -->
				<div id="center_column">